import {
  Phc,
  Medicine,
  InventoryItem,
  Prediction,
  Alert,
  Transfer,
  DashboardSummary,
  SimulationScenario,
  BloodBank,
  EmergencyBloodRequest,
  BloodTransfer,
  BloodDashboardSummary
} from '../types';

export const MOCK_PHCS: Phc[] = [
  {
    "id": 1,
    "name": "Alandi PHC-1",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.583142,
    "longitude": 73.642955,
    "populationServed": 27606,
    "isActive": true
  },
  {
    "id": 2,
    "name": "Shirwal PHC-2",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.626812,
    "longitude": 73.936215,
    "populationServed": 30196,
    "isActive": true
  },
  {
    "id": 3,
    "name": "Wai PHC-3",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.393787,
    "longitude": 73.85911,
    "populationServed": 35999,
    "isActive": true
  },
  {
    "id": 4,
    "name": "Khed PHC-4",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.394598,
    "longitude": 73.89687,
    "populationServed": 48267,
    "isActive": true
  },
  {
    "id": 5,
    "name": "Bhor PHC-5",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.448513,
    "longitude": 73.701666,
    "populationServed": 42006,
    "isActive": true
  },
  {
    "id": 6,
    "name": "Saswad PHC-6",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.337136,
    "longitude": 73.675222,
    "populationServed": 45528,
    "isActive": true
  },
  {
    "id": 7,
    "name": "Junnar PHC-7",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.658608,
    "longitude": 73.960079,
    "populationServed": 55711,
    "isActive": true
  },
  {
    "id": 8,
    "name": "Baramati PHC-8",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.46574,
    "longitude": 73.880118,
    "populationServed": 45267,
    "isActive": true
  },
  {
    "id": 9,
    "name": "Indapur PHC-9",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.683168,
    "longitude": 73.891508,
    "populationServed": 34267,
    "isActive": true
  },
  {
    "id": 10,
    "name": "Daund PHC-10",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.397954,
    "longitude": 73.761925,
    "populationServed": 24713,
    "isActive": true
  },
  {
    "id": 11,
    "name": "Manchar PHC-11",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.340851,
    "longitude": 73.756788,
    "populationServed": 34256,
    "isActive": true
  },
  {
    "id": 12,
    "name": "Loni PHC-12",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.461981,
    "longitude": 73.725978,
    "populationServed": 36769,
    "isActive": true
  },
  {
    "id": 13,
    "name": "Sinnar PHC-13",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.372412,
    "longitude": 73.959807,
    "populationServed": 24769,
    "isActive": true
  },
  {
    "id": 14,
    "name": "Yeola PHC-14",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.740686,
    "longitude": 73.9197,
    "populationServed": 33773,
    "isActive": true
  },
  {
    "id": 15,
    "name": "Niphad PHC-15",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.674683,
    "longitude": 73.9809,
    "populationServed": 28054,
    "isActive": true
  },
  {
    "id": 16,
    "name": "Trimbak PHC-16",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.390342,
    "longitude": 74.056009,
    "populationServed": 39558,
    "isActive": true
  },
  {
    "id": 17,
    "name": "Dindori PHC-17",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.590347,
    "longitude": 73.809734,
    "populationServed": 43414,
    "isActive": true
  },
  {
    "id": 18,
    "name": "Igatpuri PHC-18",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.414596,
    "longitude": 73.742682,
    "populationServed": 32393,
    "isActive": true
  },
  {
    "id": 19,
    "name": "Chandwad PHC-19",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.558464,
    "longitude": 74.03572,
    "populationServed": 29576,
    "isActive": true
  },
  {
    "id": 20,
    "name": "Deola PHC-20",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.744292,
    "longitude": 73.860987,
    "populationServed": 19942,
    "isActive": true
  },
  {
    "id": 21,
    "name": "Karad PHC-21",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.651836,
    "longitude": 73.821672,
    "populationServed": 23092,
    "isActive": true
  },
  {
    "id": 22,
    "name": "Patan PHC-22",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.743655,
    "longitude": 73.869801,
    "populationServed": 36986,
    "isActive": true
  },
  {
    "id": 23,
    "name": "Mahabaleshwar PHC-23",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.415471,
    "longitude": 73.920133,
    "populationServed": 23277,
    "isActive": true
  },
  {
    "id": 24,
    "name": "Phaltan PHC-24",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.499576,
    "longitude": 74.060917,
    "populationServed": 38903,
    "isActive": true
  },
  {
    "id": 25,
    "name": "Koregaon PHC-25",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.520664,
    "longitude": 73.712093,
    "populationServed": 24601,
    "isActive": true
  },
  {
    "id": 26,
    "name": "Khandala PHC-26",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 20.046537,
    "longitude": 73.633578,
    "populationServed": 39911,
    "isActive": true
  },
  {
    "id": 27,
    "name": "Medha PHC-27",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 20.122882,
    "longitude": 73.803459,
    "populationServed": 28634,
    "isActive": true
  },
  {
    "id": 28,
    "name": "Rahuri PHC-28",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 20.167604,
    "longitude": 73.990927,
    "populationServed": 22120,
    "isActive": true
  },
  {
    "id": 29,
    "name": "Sangamner PHC-29",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 19.803646,
    "longitude": 73.907071,
    "populationServed": 35625,
    "isActive": true
  },
  {
    "id": 30,
    "name": "Kopargaon PHC-30",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 19.986377,
    "longitude": 73.812212,
    "populationServed": 29976,
    "isActive": true
  },
  {
    "id": 31,
    "name": "Shrirampur PHC-31",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 20.015183,
    "longitude": 73.893269,
    "populationServed": 25946,
    "isActive": true
  },
  {
    "id": 32,
    "name": "Parner PHC-32",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 20.220317,
    "longitude": 73.857245,
    "populationServed": 29583,
    "isActive": true
  },
  {
    "id": 33,
    "name": "Shevgaon PHC-33",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 19.826952,
    "longitude": 73.665914,
    "populationServed": 26405,
    "isActive": true
  },
  {
    "id": 34,
    "name": "Nevasa PHC-34",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 19.876052,
    "longitude": 73.663898,
    "populationServed": 18981,
    "isActive": true
  },
  {
    "id": 35,
    "name": "Pathardi PHC-35",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 19.875524,
    "longitude": 73.972239,
    "populationServed": 22260,
    "isActive": true
  },
  {
    "id": 36,
    "name": "Kagal PHC-36",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 19.868907,
    "longitude": 73.62434,
    "populationServed": 48312,
    "isActive": true
  },
  {
    "id": 37,
    "name": "Panhala PHC-37",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 19.985202,
    "longitude": 73.917879,
    "populationServed": 36786,
    "isActive": true
  },
  {
    "id": 38,
    "name": "Shirol PHC-38",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 19.816119,
    "longitude": 73.758773,
    "populationServed": 29392,
    "isActive": true
  },
  {
    "id": 39,
    "name": "Hatkanangle PHC-39",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 20.100584,
    "longitude": 73.867814,
    "populationServed": 29342,
    "isActive": true
  },
  {
    "id": 40,
    "name": "Radhanagari PHC-40",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 20.160253,
    "longitude": 73.676695,
    "populationServed": 24563,
    "isActive": true
  },
  {
    "id": 41,
    "name": "Bhudargad PHC-41",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 19.962347,
    "longitude": 73.690145,
    "populationServed": 26215,
    "isActive": true
  },
  {
    "id": 42,
    "name": "Ajara PHC-42",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 20.020146,
    "longitude": 73.587565,
    "populationServed": 37398,
    "isActive": true
  },
  {
    "id": 43,
    "name": "Chandgad PHC-43",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 19.991039,
    "longitude": 73.660986,
    "populationServed": 29879,
    "isActive": true
  },
  {
    "id": 44,
    "name": "Gadhinglaj PHC-44",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 19.943038,
    "longitude": 74.008189,
    "populationServed": 19607,
    "isActive": true
  },
  {
    "id": 45,
    "name": "Alandi PHC-45",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 19.977254,
    "longitude": 73.755153,
    "populationServed": 34027,
    "isActive": true
  },
  {
    "id": 46,
    "name": "Shirwal PHC-46",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.525159,
    "longitude": 73.926819,
    "populationServed": 33584,
    "isActive": true
  },
  {
    "id": 47,
    "name": "Wai PHC-47",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.481224,
    "longitude": 74.05618,
    "populationServed": 31517,
    "isActive": true
  },
  {
    "id": 48,
    "name": "Khed PHC-48",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.526345,
    "longitude": 74.225651,
    "populationServed": 25054,
    "isActive": true
  },
  {
    "id": 49,
    "name": "Bhor PHC-49",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.723266,
    "longitude": 74.097146,
    "populationServed": 27473,
    "isActive": true
  },
  {
    "id": 50,
    "name": "Saswad PHC-50",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.856129,
    "longitude": 73.904097,
    "populationServed": 34769,
    "isActive": true
  },
  {
    "id": 51,
    "name": "Junnar PHC-51",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.644151,
    "longitude": 74.055953,
    "populationServed": 36302,
    "isActive": true
  },
  {
    "id": 52,
    "name": "Baramati PHC-52",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.547417,
    "longitude": 74.115586,
    "populationServed": 25965,
    "isActive": true
  },
  {
    "id": 53,
    "name": "Indapur PHC-53",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.757761,
    "longitude": 73.928299,
    "populationServed": 22749,
    "isActive": true
  },
  {
    "id": 54,
    "name": "Daund PHC-54",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.488144,
    "longitude": 73.999528,
    "populationServed": 24770,
    "isActive": true
  },
  {
    "id": 55,
    "name": "Manchar PHC-55",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.57484,
    "longitude": 74.213267,
    "populationServed": 29247,
    "isActive": true
  },
  {
    "id": 56,
    "name": "Loni PHC-56",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.830685,
    "longitude": 74.109893,
    "populationServed": 37953,
    "isActive": true
  },
  {
    "id": 57,
    "name": "Sinnar PHC-57",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.754025,
    "longitude": 74.215819,
    "populationServed": 21434,
    "isActive": true
  },
  {
    "id": 58,
    "name": "Yeola PHC-58",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.578057,
    "longitude": 74.065473,
    "populationServed": 35143,
    "isActive": true
  },
  {
    "id": 59,
    "name": "Niphad PHC-59",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.740907,
    "longitude": 73.912093,
    "populationServed": 29674,
    "isActive": true
  },
  {
    "id": 60,
    "name": "Trimbak PHC-60",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.836247,
    "longitude": 73.834834,
    "populationServed": 29872,
    "isActive": true
  },
  {
    "id": 61,
    "name": "Dindori PHC-61",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.457096,
    "longitude": 74.140304,
    "populationServed": 33849,
    "isActive": true
  },
  {
    "id": 62,
    "name": "Igatpuri PHC-62",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.789054,
    "longitude": 74.041556,
    "populationServed": 30293,
    "isActive": true
  },
  {
    "id": 63,
    "name": "Chandwad PHC-63",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.48936,
    "longitude": 74.190698,
    "populationServed": 45763,
    "isActive": true
  },
  {
    "id": 64,
    "name": "Deola PHC-64",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.831068,
    "longitude": 74.055429,
    "populationServed": 26292,
    "isActive": true
  },
  {
    "id": 65,
    "name": "Karad PHC-65",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.594216,
    "longitude": 74.197842,
    "populationServed": 38816,
    "isActive": true
  },
  {
    "id": 66,
    "name": "Patan PHC-66",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 18.982088,
    "longitude": 74.569257,
    "populationServed": 28117,
    "isActive": true
  },
  {
    "id": 67,
    "name": "Mahabaleshwar PHC-67",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 18.939349,
    "longitude": 74.941446,
    "populationServed": 37487,
    "isActive": true
  },
  {
    "id": 68,
    "name": "Phaltan PHC-68",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 19.224119,
    "longitude": 74.571643,
    "populationServed": 16333,
    "isActive": true
  },
  {
    "id": 69,
    "name": "Koregaon PHC-69",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 19.076936,
    "longitude": 74.660336,
    "populationServed": 36827,
    "isActive": true
  },
  {
    "id": 70,
    "name": "Khandala PHC-70",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 18.880449,
    "longitude": 74.609908,
    "populationServed": 18160,
    "isActive": true
  },
  {
    "id": 71,
    "name": "Medha PHC-71",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 19.3049,
    "longitude": 74.648606,
    "populationServed": 34581,
    "isActive": true
  },
  {
    "id": 72,
    "name": "Rahuri PHC-72",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 19.311317,
    "longitude": 74.764297,
    "populationServed": 40948,
    "isActive": true
  },
  {
    "id": 73,
    "name": "Sangamner PHC-73",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 18.918581,
    "longitude": 74.718554,
    "populationServed": 36055,
    "isActive": true
  },
  {
    "id": 74,
    "name": "Kopargaon PHC-74",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 19.142594,
    "longitude": 74.75314,
    "populationServed": 27825,
    "isActive": true
  },
  {
    "id": 75,
    "name": "Shrirampur PHC-75",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 18.984425,
    "longitude": 74.841953,
    "populationServed": 33149,
    "isActive": true
  },
  {
    "id": 76,
    "name": "Parner PHC-76",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 19.203678,
    "longitude": 74.824783,
    "populationServed": 29359,
    "isActive": true
  },
  {
    "id": 77,
    "name": "Shevgaon PHC-77",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 19.168707,
    "longitude": 74.67159,
    "populationServed": 18488,
    "isActive": true
  },
  {
    "id": 78,
    "name": "Nevasa PHC-78",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 19.193689,
    "longitude": 74.658145,
    "populationServed": 27220,
    "isActive": true
  },
  {
    "id": 79,
    "name": "Pathardi PHC-79",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 19.05088,
    "longitude": 74.656045,
    "populationServed": 23722,
    "isActive": true
  },
  {
    "id": 80,
    "name": "Kagal PHC-80",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 19.292964,
    "longitude": 74.827793,
    "populationServed": 48987,
    "isActive": true
  },
  {
    "id": 81,
    "name": "Panhala PHC-81",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 19.005227,
    "longitude": 74.769572,
    "populationServed": 29097,
    "isActive": true
  },
  {
    "id": 82,
    "name": "Shirol PHC-82",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 19.164418,
    "longitude": 74.732245,
    "populationServed": 30286,
    "isActive": true
  },
  {
    "id": 83,
    "name": "Hatkanangle PHC-83",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 19.082734,
    "longitude": 74.928531,
    "populationServed": 36421,
    "isActive": true
  },
  {
    "id": 84,
    "name": "Radhanagari PHC-84",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 18.907958,
    "longitude": 74.754953,
    "populationServed": 34056,
    "isActive": true
  },
  {
    "id": 85,
    "name": "Bhudargad PHC-85",
    "district": "Ahmednagar",
    "state": "Maharashtra",
    "latitude": 19.238091,
    "longitude": 74.861012,
    "populationServed": 34392,
    "isActive": true
  },
  {
    "id": 86,
    "name": "Ajara PHC-86",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.569608,
    "longitude": 74.029291,
    "populationServed": 25374,
    "isActive": true
  },
  {
    "id": 87,
    "name": "Chandgad PHC-87",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.862382,
    "longitude": 74.051073,
    "populationServed": 28307,
    "isActive": true
  },
  {
    "id": 88,
    "name": "Gadhinglaj PHC-88",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.567496,
    "longitude": 74.331659,
    "populationServed": 31157,
    "isActive": true
  },
  {
    "id": 89,
    "name": "Alandi PHC-89",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.775226,
    "longitude": 74.020795,
    "populationServed": 49914,
    "isActive": true
  },
  {
    "id": 90,
    "name": "Shirwal PHC-90",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.527964,
    "longitude": 74.209616,
    "populationServed": 31511,
    "isActive": true
  },
  {
    "id": 91,
    "name": "Wai PHC-91",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.592139,
    "longitude": 74.400051,
    "populationServed": 28451,
    "isActive": true
  },
  {
    "id": 92,
    "name": "Khed PHC-92",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.78041,
    "longitude": 74.462852,
    "populationServed": 70926,
    "isActive": true
  },
  {
    "id": 93,
    "name": "Bhor PHC-93",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.881142,
    "longitude": 74.293994,
    "populationServed": 37793,
    "isActive": true
  },
  {
    "id": 94,
    "name": "Saswad PHC-94",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.853756,
    "longitude": 74.264842,
    "populationServed": 30802,
    "isActive": true
  },
  {
    "id": 95,
    "name": "Junnar PHC-95",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.591258,
    "longitude": 74.305248,
    "populationServed": 39662,
    "isActive": true
  },
  {
    "id": 96,
    "name": "Baramati PHC-96",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.762037,
    "longitude": 74.141869,
    "populationServed": 24253,
    "isActive": true
  },
  {
    "id": 97,
    "name": "Indapur PHC-97",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.602272,
    "longitude": 74.162169,
    "populationServed": 31888,
    "isActive": true
  },
  {
    "id": 98,
    "name": "Daund PHC-98",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.584068,
    "longitude": 74.330577,
    "populationServed": 34358,
    "isActive": true
  },
  {
    "id": 99,
    "name": "Manchar PHC-99",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.66342,
    "longitude": 74.262475,
    "populationServed": 29865,
    "isActive": true
  },
  {
    "id": 100,
    "name": "Loni PHC-100",
    "district": "Kolhapur",
    "state": "Maharashtra",
    "latitude": 16.669065,
    "longitude": 74.425477,
    "populationServed": 35187,
    "isActive": true
  }
];

export const MOCK_MEDICINES: Medicine[] = [
  {
    "id": 1,
    "code": "MED-001",
    "name": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "shelfLifeDays": 730,
    "requiresColdChain": false
  },
  {
    "id": 2,
    "code": "MED-002",
    "name": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "shelfLifeDays": 730,
    "requiresColdChain": false
  },
  {
    "id": 3,
    "code": "MED-003",
    "name": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "shelfLifeDays": 730,
    "requiresColdChain": false
  },
  {
    "id": 4,
    "code": "MED-004",
    "name": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "shelfLifeDays": 730,
    "requiresColdChain": false
  },
  {
    "id": 5,
    "code": "MED-005",
    "name": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "shelfLifeDays": 1095,
    "requiresColdChain": false
  },
  {
    "id": 6,
    "code": "MED-006",
    "name": "Ibuprofen 400mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 1200,
    "shelfLifeDays": 730,
    "requiresColdChain": false
  },
  {
    "id": 7,
    "code": "MED-007",
    "name": "Oral Rehydration Salts (ORS)",
    "category": "Maternal & Child Health",
    "unit": "Sachet",
    "safetyStock": 2000,
    "shelfLifeDays": 730,
    "requiresColdChain": false
  },
  {
    "id": 8,
    "code": "MED-008",
    "name": "Zinc Sulfate 20mg",
    "category": "Maternal & Child Health",
    "unit": "Tablet",
    "safetyStock": 1500,
    "shelfLifeDays": 730,
    "requiresColdChain": false
  },
  {
    "id": 9,
    "code": "MED-009",
    "name": "Iron Folic Acid (IFA Large)",
    "category": "Maternal & Child Health",
    "unit": "Tablet",
    "safetyStock": 2500,
    "shelfLifeDays": 730,
    "requiresColdChain": false
  },
  {
    "id": 10,
    "code": "MED-010",
    "name": "Albendazole 400mg",
    "category": "Maternal & Child Health",
    "unit": "Chewable Tablet",
    "safetyStock": 800,
    "shelfLifeDays": 1095,
    "requiresColdChain": false
  },
  {
    "id": 11,
    "code": "MED-011",
    "name": "Oxytocin 10 IU/ml",
    "category": "Maternal & Child Health",
    "unit": "Ampoule",
    "safetyStock": 300,
    "shelfLifeDays": 730,
    "requiresColdChain": true
  },
  {
    "id": 12,
    "code": "MED-012",
    "name": "Metformin 500mg",
    "category": "Chronic Care",
    "unit": "Tablet",
    "safetyStock": 2500,
    "shelfLifeDays": 1095,
    "requiresColdChain": false
  },
  {
    "id": 13,
    "code": "MED-013",
    "name": "Amlodipine 5mg",
    "category": "Chronic Care",
    "unit": "Tablet",
    "safetyStock": 2000,
    "shelfLifeDays": 1095,
    "requiresColdChain": false
  },
  {
    "id": 14,
    "code": "MED-014",
    "name": "Atenolol 50mg",
    "category": "Chronic Care",
    "unit": "Tablet",
    "safetyStock": 1500,
    "shelfLifeDays": 730,
    "requiresColdChain": false
  },
  {
    "id": 15,
    "code": "MED-015",
    "name": "Enalapril 5mg",
    "category": "Chronic Care",
    "unit": "Tablet",
    "safetyStock": 1200,
    "shelfLifeDays": 730,
    "requiresColdChain": false
  },
  {
    "id": 16,
    "code": "MED-016",
    "name": "Anti-Snake Venom (ASV Polyvalent)",
    "category": "Emergency & Critical",
    "unit": "Vial",
    "safetyStock": 50,
    "shelfLifeDays": 730,
    "requiresColdChain": true
  },
  {
    "id": 17,
    "code": "MED-017",
    "name": "Anti-Rabies Vaccine (ARV)",
    "category": "Emergency & Critical",
    "unit": "Vial",
    "safetyStock": 150,
    "shelfLifeDays": 730,
    "requiresColdChain": true
  },
  {
    "id": 18,
    "code": "MED-018",
    "name": "Dexamethasone 4mg/ml",
    "category": "Emergency & Critical",
    "unit": "Ampoule",
    "safetyStock": 400,
    "shelfLifeDays": 730,
    "requiresColdChain": false
  },
  {
    "id": 19,
    "code": "MED-019",
    "name": "Atropine Sulfate 0.6mg/ml",
    "category": "Emergency & Critical",
    "unit": "Ampoule",
    "safetyStock": 200,
    "shelfLifeDays": 730,
    "requiresColdChain": false
  },
  {
    "id": 20,
    "code": "MED-020",
    "name": "Salbutamol Inhaler 100mcg",
    "category": "Emergency & Critical",
    "unit": "Inhaler",
    "safetyStock": 350,
    "shelfLifeDays": 730,
    "requiresColdChain": false
  }
];

export const MOCK_ALERTS: Alert[] = [
  {
    "phcId": 1,
    "phcName": "Alandi PHC-1",
    "district": "Pune",
    "medicineId": 5,
    "medicineName": "Paracetamol 500mg",
    "currentStock": 120,
    "dailyDemand": 180.5,
    "daysRemaining": 0.7,
    "riskLevel": "CRITICAL",
    "message": "Critical stock-out expected in < 24 hours. Immediate inter-facility transfer recommended.",
    "timestamp": "2026-09-19T01:58:12.061Z"
  },
  {
    "phcId": 2,
    "phcName": "Shirwal PHC-2",
    "district": "Pune",
    "medicineId": 16,
    "medicineName": "Anti-Snake Venom (ASV Polyvalent)",
    "currentStock": 2,
    "dailyDemand": 3.1,
    "daysRemaining": 0.6,
    "riskLevel": "CRITICAL",
    "message": "Life-saving anti-venom below emergency reserve in high-incidence rural belt.",
    "timestamp": "2026-09-19T01:45:12.063Z"
  },
  {
    "phcId": 3,
    "phcName": "Wai PHC-3",
    "district": "Pune",
    "medicineId": 1,
    "medicineName": "Amoxicillin 500mg",
    "currentStock": 250,
    "dailyDemand": 160,
    "daysRemaining": 1.6,
    "riskLevel": "CRITICAL",
    "message": "Antibiotic inventory exhausted due to seasonal respiratory infection surge.",
    "timestamp": "2026-09-19T00:33:12.063Z"
  },
  {
    "phcId": 4,
    "phcName": "Khed PHC-4",
    "district": "Pune",
    "medicineId": 7,
    "medicineName": "Oral Rehydration Salts (ORS)",
    "currentStock": 400,
    "dailyDemand": 220,
    "daysRemaining": 1.8,
    "riskLevel": "CRITICAL",
    "message": "Gastroenteritis outbreak spike depleted pediatric ORS sachets.",
    "timestamp": "2026-09-19T00:03:12.063Z"
  },
  {
    "phcId": 5,
    "phcName": "Bhor PHC-5",
    "district": "Pune",
    "medicineId": 17,
    "medicineName": "Anti-Rabies Vaccine (ARV)",
    "currentStock": 6,
    "dailyDemand": 3.5,
    "daysRemaining": 1.7,
    "riskLevel": "CRITICAL",
    "message": "Rabies post-exposure prophylaxis protocol stock critical.",
    "timestamp": "2026-09-18T23:33:12.063Z"
  },
  {
    "phcId": 6,
    "phcName": "Saswad PHC-6",
    "district": "Pune",
    "medicineId": 11,
    "medicineName": "Oxytocin 10 IU/ml",
    "currentStock": 25,
    "dailyDemand": 12,
    "daysRemaining": 2.1,
    "riskLevel": "CRITICAL",
    "message": "Maternal labor ward emergency oxytocin reserves below 3 days.",
    "timestamp": "2026-09-18T23:03:12.063Z"
  },
  {
    "phcId": 7,
    "phcName": "Junnar PHC-7",
    "district": "Pune",
    "medicineId": 12,
    "medicineName": "Metformin 500mg",
    "currentStock": 800,
    "dailyDemand": 350,
    "daysRemaining": 2.3,
    "riskLevel": "HIGH",
    "message": "Chronic NCD dispensary runs low stock for rural diabetic cohort.",
    "timestamp": "2026-09-18T22:33:12.063Z"
  },
  {
    "phcId": 8,
    "phcName": "Baramati PHC-8",
    "district": "Pune",
    "medicineId": 13,
    "medicineName": "Amlodipine 5mg",
    "currentStock": 600,
    "dailyDemand": 240,
    "daysRemaining": 2.5,
    "riskLevel": "HIGH",
    "message": "Hypertension maintenance protocol medication nearing safety stock trigger.",
    "timestamp": "2026-09-18T21:33:12.063Z"
  },
  {
    "phcId": 13,
    "phcName": "Sinnar PHC-13",
    "district": "Nashik",
    "medicineId": 5,
    "medicineName": "Paracetamol 500mg",
    "currentStock": 350,
    "dailyDemand": 165,
    "daysRemaining": 2.1,
    "riskLevel": "CRITICAL",
    "message": "Monsoon fever OPD footfall elevated demand beyond local reserve.",
    "timestamp": "2026-09-18T21:13:12.063Z"
  },
  {
    "phcId": 14,
    "phcName": "Yeola PHC-14",
    "district": "Nashik",
    "medicineId": 3,
    "medicineName": "Ciprofloxacin 500mg",
    "currentStock": 280,
    "dailyDemand": 110,
    "daysRemaining": 2.5,
    "riskLevel": "HIGH",
    "message": "Water-borne infection treatments required in Yeola agrarian cluster.",
    "timestamp": "2026-09-18T20:33:12.063Z"
  },
  {
    "phcId": 21,
    "phcName": "Karad PHC-21",
    "district": "Satara",
    "medicineId": 16,
    "medicineName": "Anti-Snake Venom (ASV Polyvalent)",
    "currentStock": 3,
    "dailyDemand": 1.8,
    "daysRemaining": 1.6,
    "riskLevel": "CRITICAL",
    "message": "Riverine agricultural valley urgent anti-venom replenish required.",
    "timestamp": "2026-09-18T19:53:12.063Z"
  },
  {
    "phcId": 23,
    "phcName": "Mahabaleshwar PHC-23",
    "district": "Satara",
    "medicineId": 20,
    "medicineName": "Salbutamol Inhaler 100mcg",
    "currentStock": 15,
    "dailyDemand": 7.2,
    "daysRemaining": 2,
    "riskLevel": "HIGH",
    "message": "High altitude pediatric respiratory exacerbations elevated consumption.",
    "timestamp": "2026-09-18T19:33:12.063Z"
  }
];

export const MOCK_DASHBOARD_SUMMARY: DashboardSummary = {
  "totalPhcsMonitored": 100,
  "totalMedicinesTracked": 20,
  "criticalStockouts": 14,
  "highRiskPredictions": 23,
  "pendingTransfers": 8,
  "completedTransfers": 42,
  "networkHealthScore": 96.4,
  "districtSummaries": [
    {
      "district": "Pune",
      "totalPhcs": 25,
      "criticalPhcs": 6,
      "highRiskPhcs": 8,
      "averageDaysRemaining": 5.4,
      "overallStatus": "CRITICAL ATTENTION"
    },
    {
      "district": "Nashik",
      "totalPhcs": 20,
      "criticalPhcs": 3,
      "highRiskPhcs": 5,
      "averageDaysRemaining": 8.2,
      "overallStatus": "MONITORING"
    },
    {
      "district": "Satara",
      "totalPhcs": 20,
      "criticalPhcs": 3,
      "highRiskPhcs": 4,
      "averageDaysRemaining": 7.9,
      "overallStatus": "ACTION REQUIRED"
    },
    {
      "district": "Ahmednagar",
      "totalPhcs": 18,
      "criticalPhcs": 1,
      "highRiskPhcs": 3,
      "averageDaysRemaining": 12.1,
      "overallStatus": "NORMAL"
    },
    {
      "district": "Kolhapur",
      "totalPhcs": 17,
      "criticalPhcs": 1,
      "highRiskPhcs": 3,
      "averageDaysRemaining": 11.5,
      "overallStatus": "NORMAL"
    }
  ]
};

export const MOCK_INVENTORIES: InventoryItem[] = [
  {
    "id": 1,
    "phcId": 1,
    "phcName": "Alandi PHC-1",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 150,
    "reservedQuantity": 0,
    "availableQuantity": 150,
    "batchNumber": "BATCH-2026-102",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 2,
    "phcId": 1,
    "phcName": "Alandi PHC-1",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 90,
    "reservedQuantity": 0,
    "availableQuantity": 90,
    "batchNumber": "BATCH-2026-103",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 3,
    "phcId": 1,
    "phcName": "Alandi PHC-1",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-104",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 4,
    "phcId": 1,
    "phcName": "Alandi PHC-1",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-105",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 5,
    "phcId": 1,
    "phcName": "Alandi PHC-1",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-106",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 6,
    "phcId": 2,
    "phcName": "Shirwal PHC-2",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 150,
    "reservedQuantity": 0,
    "availableQuantity": 150,
    "batchNumber": "BATCH-2026-107",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 7,
    "phcId": 2,
    "phcName": "Shirwal PHC-2",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 90,
    "reservedQuantity": 0,
    "availableQuantity": 90,
    "batchNumber": "BATCH-2026-108",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 8,
    "phcId": 2,
    "phcName": "Shirwal PHC-2",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-109",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 9,
    "phcId": 2,
    "phcName": "Shirwal PHC-2",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-110",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 10,
    "phcId": 2,
    "phcName": "Shirwal PHC-2",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-111",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 11,
    "phcId": 3,
    "phcName": "Wai PHC-3",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 150,
    "reservedQuantity": 0,
    "availableQuantity": 150,
    "batchNumber": "BATCH-2026-112",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 12,
    "phcId": 3,
    "phcName": "Wai PHC-3",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 90,
    "reservedQuantity": 0,
    "availableQuantity": 90,
    "batchNumber": "BATCH-2026-113",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 13,
    "phcId": 3,
    "phcName": "Wai PHC-3",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-114",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 14,
    "phcId": 3,
    "phcName": "Wai PHC-3",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-115",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 15,
    "phcId": 3,
    "phcName": "Wai PHC-3",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-116",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 16,
    "phcId": 4,
    "phcName": "Khed PHC-4",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 1800,
    "reservedQuantity": 50,
    "availableQuantity": 1750,
    "batchNumber": "BATCH-2026-117",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 17,
    "phcId": 4,
    "phcName": "Khed PHC-4",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 1080,
    "reservedQuantity": 50,
    "availableQuantity": 1030,
    "batchNumber": "BATCH-2026-118",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 18,
    "phcId": 4,
    "phcName": "Khed PHC-4",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-119",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 19,
    "phcId": 4,
    "phcName": "Khed PHC-4",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-120",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 20,
    "phcId": 4,
    "phcName": "Khed PHC-4",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-121",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 21,
    "phcId": 5,
    "phcName": "Bhor PHC-5",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 1800,
    "reservedQuantity": 50,
    "availableQuantity": 1750,
    "batchNumber": "BATCH-2026-122",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 22,
    "phcId": 5,
    "phcName": "Bhor PHC-5",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 1080,
    "reservedQuantity": 50,
    "availableQuantity": 1030,
    "batchNumber": "BATCH-2026-123",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 23,
    "phcId": 5,
    "phcName": "Bhor PHC-5",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-124",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 24,
    "phcId": 5,
    "phcName": "Bhor PHC-5",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-125",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 25,
    "phcId": 5,
    "phcName": "Bhor PHC-5",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-126",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 26,
    "phcId": 6,
    "phcName": "Saswad PHC-6",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 1800,
    "reservedQuantity": 50,
    "availableQuantity": 1750,
    "batchNumber": "BATCH-2026-127",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 27,
    "phcId": 6,
    "phcName": "Saswad PHC-6",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 1080,
    "reservedQuantity": 50,
    "availableQuantity": 1030,
    "batchNumber": "BATCH-2026-128",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 28,
    "phcId": 6,
    "phcName": "Saswad PHC-6",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-129",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 29,
    "phcId": 6,
    "phcName": "Saswad PHC-6",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-130",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 30,
    "phcId": 6,
    "phcName": "Saswad PHC-6",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-131",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 31,
    "phcId": 7,
    "phcName": "Junnar PHC-7",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 1800,
    "reservedQuantity": 50,
    "availableQuantity": 1750,
    "batchNumber": "BATCH-2026-132",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 32,
    "phcId": 7,
    "phcName": "Junnar PHC-7",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 1080,
    "reservedQuantity": 50,
    "availableQuantity": 1030,
    "batchNumber": "BATCH-2026-133",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 33,
    "phcId": 7,
    "phcName": "Junnar PHC-7",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-134",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 34,
    "phcId": 7,
    "phcName": "Junnar PHC-7",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-135",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 35,
    "phcId": 7,
    "phcName": "Junnar PHC-7",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-136",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 36,
    "phcId": 8,
    "phcName": "Baramati PHC-8",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 1800,
    "reservedQuantity": 50,
    "availableQuantity": 1750,
    "batchNumber": "BATCH-2026-137",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 37,
    "phcId": 8,
    "phcName": "Baramati PHC-8",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 1080,
    "reservedQuantity": 50,
    "availableQuantity": 1030,
    "batchNumber": "BATCH-2026-138",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 38,
    "phcId": 8,
    "phcName": "Baramati PHC-8",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-139",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 39,
    "phcId": 8,
    "phcName": "Baramati PHC-8",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-140",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 40,
    "phcId": 8,
    "phcName": "Baramati PHC-8",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-141",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 41,
    "phcId": 9,
    "phcName": "Indapur PHC-9",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 1800,
    "reservedQuantity": 50,
    "availableQuantity": 1750,
    "batchNumber": "BATCH-2026-142",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 42,
    "phcId": 9,
    "phcName": "Indapur PHC-9",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 1080,
    "reservedQuantity": 50,
    "availableQuantity": 1030,
    "batchNumber": "BATCH-2026-143",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 43,
    "phcId": 9,
    "phcName": "Indapur PHC-9",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-144",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 44,
    "phcId": 9,
    "phcName": "Indapur PHC-9",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-145",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 45,
    "phcId": 9,
    "phcName": "Indapur PHC-9",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-146",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 46,
    "phcId": 10,
    "phcName": "Daund PHC-10",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 1800,
    "reservedQuantity": 50,
    "availableQuantity": 1750,
    "batchNumber": "BATCH-2026-147",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 47,
    "phcId": 10,
    "phcName": "Daund PHC-10",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 1080,
    "reservedQuantity": 50,
    "availableQuantity": 1030,
    "batchNumber": "BATCH-2026-148",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 48,
    "phcId": 10,
    "phcName": "Daund PHC-10",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-149",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 49,
    "phcId": 10,
    "phcName": "Daund PHC-10",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-150",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 50,
    "phcId": 10,
    "phcName": "Daund PHC-10",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-151",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 51,
    "phcId": 11,
    "phcName": "Manchar PHC-11",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 1800,
    "reservedQuantity": 50,
    "availableQuantity": 1750,
    "batchNumber": "BATCH-2026-152",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 52,
    "phcId": 11,
    "phcName": "Manchar PHC-11",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 1080,
    "reservedQuantity": 50,
    "availableQuantity": 1030,
    "batchNumber": "BATCH-2026-153",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 53,
    "phcId": 11,
    "phcName": "Manchar PHC-11",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-154",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 54,
    "phcId": 11,
    "phcName": "Manchar PHC-11",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-155",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 55,
    "phcId": 11,
    "phcName": "Manchar PHC-11",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-156",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 56,
    "phcId": 12,
    "phcName": "Loni PHC-12",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 1800,
    "reservedQuantity": 50,
    "availableQuantity": 1750,
    "batchNumber": "BATCH-2026-157",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 57,
    "phcId": 12,
    "phcName": "Loni PHC-12",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 1080,
    "reservedQuantity": 50,
    "availableQuantity": 1030,
    "batchNumber": "BATCH-2026-158",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 58,
    "phcId": 12,
    "phcName": "Loni PHC-12",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-159",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 59,
    "phcId": 12,
    "phcName": "Loni PHC-12",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-160",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 60,
    "phcId": 12,
    "phcName": "Loni PHC-12",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-161",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 61,
    "phcId": 13,
    "phcName": "Sinnar PHC-13",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 1800,
    "reservedQuantity": 50,
    "availableQuantity": 1750,
    "batchNumber": "BATCH-2026-162",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 62,
    "phcId": 13,
    "phcName": "Sinnar PHC-13",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 1080,
    "reservedQuantity": 50,
    "availableQuantity": 1030,
    "batchNumber": "BATCH-2026-163",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 63,
    "phcId": 13,
    "phcName": "Sinnar PHC-13",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-164",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 64,
    "phcId": 13,
    "phcName": "Sinnar PHC-13",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-165",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 65,
    "phcId": 13,
    "phcName": "Sinnar PHC-13",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-166",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 66,
    "phcId": 14,
    "phcName": "Yeola PHC-14",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 1800,
    "reservedQuantity": 50,
    "availableQuantity": 1750,
    "batchNumber": "BATCH-2026-167",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 67,
    "phcId": 14,
    "phcName": "Yeola PHC-14",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 1080,
    "reservedQuantity": 50,
    "availableQuantity": 1030,
    "batchNumber": "BATCH-2026-168",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 68,
    "phcId": 14,
    "phcName": "Yeola PHC-14",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-169",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 69,
    "phcId": 14,
    "phcName": "Yeola PHC-14",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-170",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 70,
    "phcId": 14,
    "phcName": "Yeola PHC-14",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-171",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 71,
    "phcId": 15,
    "phcName": "Niphad PHC-15",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 1000,
    "quantity": 1800,
    "reservedQuantity": 50,
    "availableQuantity": 1750,
    "batchNumber": "BATCH-2026-172",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 72,
    "phcId": 15,
    "phcName": "Niphad PHC-15",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 600,
    "quantity": 1080,
    "reservedQuantity": 50,
    "availableQuantity": 1030,
    "batchNumber": "BATCH-2026-173",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 73,
    "phcId": 15,
    "phcName": "Niphad PHC-15",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "category": "Antibiotic",
    "unit": "Tablet",
    "safetyStock": 800,
    "quantity": 1440,
    "reservedQuantity": 50,
    "availableQuantity": 1390,
    "batchNumber": "BATCH-2026-174",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 74,
    "phcId": 15,
    "phcName": "Niphad PHC-15",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "category": "Antibiotic",
    "unit": "Capsule",
    "safetyStock": 500,
    "quantity": 900,
    "reservedQuantity": 50,
    "availableQuantity": 850,
    "batchNumber": "BATCH-2026-175",
    "expiryDate": "2027-08-31"
  },
  {
    "id": 75,
    "phcId": 15,
    "phcName": "Niphad PHC-15",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "category": "Analgesic/Antipyretic",
    "unit": "Tablet",
    "safetyStock": 3000,
    "quantity": 5400,
    "reservedQuantity": 50,
    "availableQuantity": 5350,
    "batchNumber": "BATCH-2026-176",
    "expiryDate": "2027-08-31"
  }
];

export const MOCK_PREDICTIONS: Prediction[] = [
  {
    "id": 1,
    "phcId": 1,
    "phcName": "Alandi PHC-1",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "predictedDailyDemand": 40,
    "predictedDaysToStockout": 1.4,
    "riskLevel": "CRITICAL",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.92,
    "createdAt": "2026-09-19T02:33:12.064Z"
  },
  {
    "id": 2,
    "phcId": 2,
    "phcName": "Shirwal PHC-2",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "predictedDailyDemand": 24,
    "predictedDaysToStockout": 1.5999999999999999,
    "riskLevel": "CRITICAL",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.93,
    "createdAt": "2026-09-19T01:48:12.064Z"
  },
  {
    "id": 3,
    "phcId": 3,
    "phcName": "Wai PHC-3",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "predictedDailyDemand": 32,
    "predictedDaysToStockout": 1.7999999999999998,
    "riskLevel": "CRITICAL",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.9400000000000001,
    "createdAt": "2026-09-19T01:03:12.065Z"
  },
  {
    "id": 4,
    "phcId": 4,
    "phcName": "Khed PHC-4",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "predictedDailyDemand": 20,
    "predictedDaysToStockout": 2,
    "riskLevel": "CRITICAL",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.9500000000000001,
    "createdAt": "2026-09-19T00:18:12.065Z"
  },
  {
    "id": 5,
    "phcId": 5,
    "phcName": "Bhor PHC-5",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "predictedDailyDemand": 120,
    "predictedDaysToStockout": 2.2,
    "riskLevel": "CRITICAL",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.9600000000000001,
    "createdAt": "2026-09-18T23:33:12.065Z"
  },
  {
    "id": 6,
    "phcId": 6,
    "phcName": "Saswad PHC-6",
    "district": "Pune",
    "medicineId": 6,
    "medicineCode": "MED-006",
    "medicineName": "Ibuprofen 400mg",
    "predictedDailyDemand": 48,
    "predictedDaysToStockout": 2.4,
    "riskLevel": "CRITICAL",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.9700000000000001,
    "createdAt": "2026-09-18T22:48:12.065Z"
  },
  {
    "id": 7,
    "phcId": 7,
    "phcName": "Junnar PHC-7",
    "district": "Pune",
    "medicineId": 7,
    "medicineCode": "MED-007",
    "medicineName": "Oral Rehydration Salts (ORS)",
    "predictedDailyDemand": 80,
    "predictedDaysToStockout": 2.6,
    "riskLevel": "CRITICAL",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.98,
    "createdAt": "2026-09-18T22:03:12.065Z"
  },
  {
    "id": 8,
    "phcId": 8,
    "phcName": "Baramati PHC-8",
    "district": "Pune",
    "medicineId": 8,
    "medicineCode": "MED-008",
    "medicineName": "Zinc Sulfate 20mg",
    "predictedDailyDemand": 60,
    "predictedDaysToStockout": 2.8,
    "riskLevel": "CRITICAL",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.92,
    "createdAt": "2026-09-18T21:18:12.065Z"
  },
  {
    "id": 9,
    "phcId": 9,
    "phcName": "Indapur PHC-9",
    "district": "Pune",
    "medicineId": 9,
    "medicineCode": "MED-009",
    "medicineName": "Iron Folic Acid (IFA Large)",
    "predictedDailyDemand": 100,
    "predictedDaysToStockout": 6.9,
    "riskLevel": "HIGH",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.93,
    "createdAt": "2026-09-18T20:33:12.065Z"
  },
  {
    "id": 10,
    "phcId": 10,
    "phcName": "Daund PHC-10",
    "district": "Pune",
    "medicineId": 10,
    "medicineCode": "MED-010",
    "medicineName": "Albendazole 400mg",
    "predictedDailyDemand": 32,
    "predictedDaysToStockout": 7.199999999999999,
    "riskLevel": "HIGH",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.9400000000000001,
    "createdAt": "2026-09-18T19:48:12.065Z"
  },
  {
    "id": 11,
    "phcId": 11,
    "phcName": "Manchar PHC-11",
    "district": "Pune",
    "medicineId": 11,
    "medicineCode": "MED-011",
    "medicineName": "Oxytocin 10 IU/ml",
    "predictedDailyDemand": 12,
    "predictedDaysToStockout": 7.5,
    "riskLevel": "HIGH",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.9500000000000001,
    "createdAt": "2026-09-18T19:03:12.065Z"
  },
  {
    "id": 12,
    "phcId": 12,
    "phcName": "Loni PHC-12",
    "district": "Pune",
    "medicineId": 12,
    "medicineCode": "MED-012",
    "medicineName": "Metformin 500mg",
    "predictedDailyDemand": 100,
    "predictedDaysToStockout": 7.8,
    "riskLevel": "HIGH",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.9600000000000001,
    "createdAt": "2026-09-18T18:18:12.065Z"
  },
  {
    "id": 13,
    "phcId": 13,
    "phcName": "Sinnar PHC-13",
    "district": "Pune",
    "medicineId": 13,
    "medicineCode": "MED-013",
    "medicineName": "Amlodipine 5mg",
    "predictedDailyDemand": 80,
    "predictedDaysToStockout": 8.1,
    "riskLevel": "HIGH",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.9700000000000001,
    "createdAt": "2026-09-18T17:33:12.065Z"
  },
  {
    "id": 14,
    "phcId": 14,
    "phcName": "Yeola PHC-14",
    "district": "Pune",
    "medicineId": 14,
    "medicineCode": "MED-014",
    "medicineName": "Atenolol 50mg",
    "predictedDailyDemand": 60,
    "predictedDaysToStockout": 8.4,
    "riskLevel": "HIGH",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.98,
    "createdAt": "2026-09-18T16:48:12.065Z"
  },
  {
    "id": 15,
    "phcId": 15,
    "phcName": "Niphad PHC-15",
    "district": "Pune",
    "medicineId": 15,
    "medicineCode": "MED-015",
    "medicineName": "Enalapril 5mg",
    "predictedDailyDemand": 48,
    "predictedDaysToStockout": 8.7,
    "riskLevel": "HIGH",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.92,
    "createdAt": "2026-09-18T16:03:12.065Z"
  },
  {
    "id": 16,
    "phcId": 16,
    "phcName": "Trimbak PHC-16",
    "district": "Pune",
    "medicineId": 16,
    "medicineCode": "MED-016",
    "medicineName": "Anti-Snake Venom (ASV Polyvalent)",
    "predictedDailyDemand": 2,
    "predictedDaysToStockout": 9,
    "riskLevel": "HIGH",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.93,
    "createdAt": "2026-09-18T15:18:12.065Z"
  },
  {
    "id": 17,
    "phcId": 17,
    "phcName": "Dindori PHC-17",
    "district": "Pune",
    "medicineId": 17,
    "medicineCode": "MED-017",
    "medicineName": "Anti-Rabies Vaccine (ARV)",
    "predictedDailyDemand": 6,
    "predictedDaysToStockout": 22,
    "riskLevel": "MEDIUM",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.9400000000000001,
    "createdAt": "2026-09-18T14:33:12.065Z"
  },
  {
    "id": 18,
    "phcId": 18,
    "phcName": "Igatpuri PHC-18",
    "district": "Pune",
    "medicineId": 18,
    "medicineCode": "MED-018",
    "medicineName": "Dexamethasone 4mg/ml",
    "predictedDailyDemand": 16,
    "predictedDaysToStockout": 22.5,
    "riskLevel": "MEDIUM",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.9500000000000001,
    "createdAt": "2026-09-18T13:48:12.065Z"
  },
  {
    "id": 19,
    "phcId": 19,
    "phcName": "Chandwad PHC-19",
    "district": "Pune",
    "medicineId": 19,
    "medicineCode": "MED-019",
    "medicineName": "Atropine Sulfate 0.6mg/ml",
    "predictedDailyDemand": 8,
    "predictedDaysToStockout": 23,
    "riskLevel": "MEDIUM",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.9600000000000001,
    "createdAt": "2026-09-18T13:03:12.065Z"
  },
  {
    "id": 20,
    "phcId": 20,
    "phcName": "Deola PHC-20",
    "district": "Pune",
    "medicineId": 20,
    "medicineCode": "MED-020",
    "medicineName": "Salbutamol Inhaler 100mcg",
    "predictedDailyDemand": 14,
    "predictedDaysToStockout": 23.5,
    "riskLevel": "MEDIUM",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.9700000000000001,
    "createdAt": "2026-09-18T12:18:12.065Z"
  },
  {
    "id": 21,
    "phcId": 21,
    "phcName": "Karad PHC-21",
    "district": "Pune",
    "medicineId": 1,
    "medicineCode": "MED-001",
    "medicineName": "Amoxicillin 500mg",
    "predictedDailyDemand": 40,
    "predictedDaysToStockout": 24,
    "riskLevel": "MEDIUM",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.98,
    "createdAt": "2026-09-18T11:33:12.065Z"
  },
  {
    "id": 22,
    "phcId": 22,
    "phcName": "Patan PHC-22",
    "district": "Pune",
    "medicineId": 2,
    "medicineCode": "MED-002",
    "medicineName": "Azithromycin 250mg",
    "predictedDailyDemand": 24,
    "predictedDaysToStockout": 24.5,
    "riskLevel": "MEDIUM",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.92,
    "createdAt": "2026-09-18T10:48:12.065Z"
  },
  {
    "id": 23,
    "phcId": 23,
    "phcName": "Mahabaleshwar PHC-23",
    "district": "Pune",
    "medicineId": 3,
    "medicineCode": "MED-003",
    "medicineName": "Ciprofloxacin 500mg",
    "predictedDailyDemand": 32,
    "predictedDaysToStockout": 25,
    "riskLevel": "MEDIUM",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.93,
    "createdAt": "2026-09-18T10:03:12.065Z"
  },
  {
    "id": 24,
    "phcId": 24,
    "phcName": "Phaltan PHC-24",
    "district": "Pune",
    "medicineId": 4,
    "medicineCode": "MED-004",
    "medicineName": "Doxycycline 100mg",
    "predictedDailyDemand": 20,
    "predictedDaysToStockout": 25.5,
    "riskLevel": "MEDIUM",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.9400000000000001,
    "createdAt": "2026-09-18T09:18:12.065Z"
  },
  {
    "id": 25,
    "phcId": 25,
    "phcName": "Koregaon PHC-25",
    "district": "Pune",
    "medicineId": 5,
    "medicineCode": "MED-005",
    "medicineName": "Paracetamol 500mg",
    "predictedDailyDemand": 120,
    "predictedDaysToStockout": 26,
    "riskLevel": "MEDIUM",
    "modelVersion": "v2.4-ensemble-xgb",
    "confidenceScore": 0.9500000000000001,
    "createdAt": "2026-09-18T08:33:12.065Z"
  }
];

export const MOCK_TRANSFERS: Transfer[] = [
  {
    "id": 1,
    "sourcePhcId": 16,
    "sourcePhcName": "Trimbak PHC-16",
    "sourceDistrict": "Pune",
    "destinationPhcId": 1,
    "destinationPhcName": "Alandi PHC-1",
    "destinationDistrict": "Pune",
    "medicineId": 5,
    "medicineName": "Paracetamol 500mg",
    "medicineUnit": "Tablet",
    "quantity": 1500,
    "distanceKm": 24.5,
    "estimatedCost": 350,
    "status": "PENDING_APPROVAL",
    "recommendationReason": "Diverting excess safety buffer from Trimbak node (32 days inventory) to resolve acute deficit at Alandi node (< 1 day remaining). Deterministic distance-penalized transport route.",
    "createdAt": "2026-09-19T01:53:12.065Z",
    "updatedAt": "2026-09-19T02:23:12.065Z"
  },
  {
    "id": 2,
    "sourcePhcId": 18,
    "sourcePhcName": "Igatpuri PHC-18",
    "sourceDistrict": "Pune",
    "destinationPhcId": 2,
    "destinationPhcName": "Shirwal PHC-2",
    "destinationDistrict": "Pune",
    "medicineId": 16,
    "medicineName": "Anti-Snake Venom (ASV Polyvalent)",
    "medicineUnit": "Vial",
    "quantity": 15,
    "distanceKm": 38.2,
    "estimatedCost": 520,
    "status": "IN_TRANSIT",
    "recommendationReason": "Emergency antivenom life-support dispatch with verified mobile cold-chain refrigeration pack (2C - 8C). Dispatch ETA: 48 minutes.",
    "createdAt": "2026-09-19T01:03:12.065Z",
    "updatedAt": "2026-09-19T02:08:12.065Z"
  },
  {
    "id": 3,
    "sourcePhcId": 24,
    "sourcePhcName": "Phaltan PHC-24",
    "sourceDistrict": "Pune",
    "destinationPhcId": 3,
    "destinationPhcName": "Wai PHC-3",
    "destinationDistrict": "Pune",
    "medicineId": 1,
    "medicineName": "Amoxicillin 500mg",
    "medicineUnit": "Capsule",
    "quantity": 800,
    "distanceKm": 29.1,
    "estimatedCost": 410,
    "status": "COMPLETED",
    "recommendationReason": "Redistributed pediatric antibiotic supply to avoid stock-out during monsoon epidemic phase.",
    "createdAt": "2026-09-18T20:33:12.065Z",
    "updatedAt": "2026-09-19T00:33:12.065Z"
  }
];

export const MOCK_SIMULATION_SCENARIOS: SimulationScenario[] = [
  {
    "scenarioId": "MONSOON_FLOOD_SURGE",
    "name": "Monsoon Flood & Waterborne Disease Outbreak",
    "description": "Simulates flash flooding across river basins causing +150% surge in ORS, Ciprofloxacin, and Anti-Snake Venom demand coupled with 4-day supply road transit delays.",
    "defaultSurgePercent": 150,
    "defaultAcuteMultiplier": 2.5,
    "defaultSupplyDelayDays": 4,
    "affectedCategory": "Maternal & Child Health",
    "riskSeverity": "CRITICAL"
  },
  {
    "scenarioId": "VIRAL_FEVER_EPIDEMIC",
    "name": "Seasonal Dengue & Viral Pyrexia Surge",
    "description": "Rapid transmission spike across dense urban-rural perimeter leading to +200% antipyretic consumption and blood component shortage.",
    "defaultSurgePercent": 200,
    "defaultAcuteMultiplier": 3,
    "defaultSupplyDelayDays": 2,
    "affectedCategory": "Analgesic/Antipyretic",
    "riskSeverity": "HIGH"
  },
  {
    "scenarioId": "SUPPLY_CHAIN_BOTTLENECK",
    "name": "State Central Medical Depot Transport Strike",
    "description": "Highway freight stoppage induces 10-day regional replenishment freeze. Evaluates PHC peer-to-peer survival autonomy.",
    "defaultSurgePercent": 20,
    "defaultAcuteMultiplier": 1,
    "defaultSupplyDelayDays": 10,
    "affectedCategory": "Emergency & Critical",
    "riskSeverity": "CRITICAL"
  }
];

export const MOCK_BLOOD_BANKS: BloodBank[] = [
  {
    "id": 1,
    "name": "Red Cross Regional Blood Centre - Pune",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.5204,
    "longitude": 73.8567,
    "verificationStatus": "VERIFIED",
    "contactPhone": "+91 20 2612 0000",
    "contactEmail": "pune.redcross@medflow.org",
    "operatingHours": "24x7 Emergency Transfusion Ready",
    "storageCapacityUnits": 1500,
    "isActive": true
  },
  {
    "id": 2,
    "name": "Jeevan Jyoti Blood Bank - Pune",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.6007,
    "longitude": 74.1352,
    "verificationStatus": "VERIFIED",
    "contactPhone": "+91 70212 30926",
    "contactEmail": "contact@jeevanjyotiblood.in",
    "operatingHours": "24x7 Emergency Unit",
    "storageCapacityUnits": 800,
    "isActive": true
  },
  {
    "id": 3,
    "name": "Sahyadri Specialty Blood Center",
    "district": "Pune",
    "state": "Maharashtra",
    "latitude": 18.5089,
    "longitude": 73.8344,
    "verificationStatus": "VERIFIED",
    "contactPhone": "+91 20 6721 3000",
    "contactEmail": "bloodbank@sahyadrihospitals.com",
    "operatingHours": "24 Hours Emergency Hub",
    "storageCapacityUnits": 1200,
    "isActive": true
  },
  {
    "id": 4,
    "name": "Nashik Metropolitan Blood Bank",
    "district": "Nashik",
    "state": "Maharashtra",
    "latitude": 20.0059,
    "longitude": 73.7915,
    "verificationStatus": "VERIFIED",
    "contactPhone": "+91 253 257 8899",
    "operatingHours": "24x7 Transfusion Wing",
    "storageCapacityUnits": 1000,
    "isActive": true
  },
  {
    "id": 5,
    "name": "Satara Life Line Blood Services",
    "district": "Satara",
    "state": "Maharashtra",
    "latitude": 17.6885,
    "longitude": 74.0041,
    "verificationStatus": "PROVISIONAL",
    "contactPhone": "+91 2162 234 567",
    "operatingHours": "08:00 - 22:00",
    "storageCapacityUnits": 600,
    "isActive": true
  }
];

export const MOCK_BLOOD_REQUESTS: EmergencyBloodRequest[] = [
  {
    "id": 101,
    "hospitalId": 1,
    "hospitalName": "Alandi PHC-1",
    "hospitalDistrict": "Pune",
    "hospitalLatitude": 18.5831,
    "hospitalLongitude": 73.6429,
    "bloodGroup": "O-",
    "componentType": "WHOLE_BLOOD",
    "unitsRequired": 3,
    "priority": "CRITICAL",
    "requiredBy": "2026-09-19T03:18:12.065Z",
    "status": "MATCH_FOUND",
    "clinicalNotes": "Urgent: Polytrauma patient in ICU emergency theater. Universal donor blood required immediately.",
    "createdByName": "Dr. S. Kulkarni (Chief Surgeon)",
    "createdAt": "2026-09-19T02:18:12.065Z",
    "updatedAt": "2026-09-19T02:28:12.065Z"
  },
  {
    "id": 102,
    "hospitalId": 2,
    "hospitalName": "Shirwal PHC-2",
    "hospitalDistrict": "Pune",
    "hospitalLatitude": 18.6268,
    "hospitalLongitude": 73.9362,
    "bloodGroup": "A+",
    "componentType": "PACKED_RED_CELLS",
    "unitsRequired": 2,
    "priority": "HIGH",
    "requiredBy": "2026-09-19T04:03:12.065Z",
    "status": "IN_TRANSIT",
    "clinicalNotes": "Postpartum hemorrhage intervention in Labor Ward.",
    "createdByName": "Dr. A. Deshmukh",
    "createdAt": "2026-09-19T01:53:12.065Z",
    "updatedAt": "2026-09-19T02:23:12.065Z"
  },
  {
    "id": 103,
    "hospitalId": 3,
    "hospitalName": "Wai PHC-3",
    "hospitalDistrict": "Pune",
    "hospitalLatitude": 18.3937,
    "hospitalLongitude": 73.8591,
    "bloodGroup": "B+",
    "componentType": "PLATELETS",
    "unitsRequired": 4,
    "priority": "MEDIUM",
    "requiredBy": "2026-09-19T05:33:12.065Z",
    "status": "FULFILLED",
    "clinicalNotes": "Dengue thrombopenia crisis stabilization completed.",
    "createdByName": "Dr. R. Patil",
    "createdAt": "2026-09-18T23:33:12.065Z",
    "updatedAt": "2026-09-19T01:33:12.065Z"
  }
];

export const MOCK_BLOOD_TRANSFERS: BloodTransfer[] = [
  {
    "id": 201,
    "requestId": 102,
    "bloodGroup": "A+",
    "units": 2,
    "sourceBloodBankId": 1,
    "sourceBloodBankName": "Red Cross Regional Blood Centre - Pune",
    "sourceDistrict": "Pune",
    "destinationHospitalId": 2,
    "destinationHospitalName": "Shirwal PHC-2",
    "destinationDistrict": "Pune",
    "estimatedDistanceKm": 31.4,
    "estimatedEtaMinutes": 42,
    "status": "IN_TRANSIT",
    "coldChainVerified": true,
    "dispatchedAt": "2026-09-19T02:18:12.065Z",
    "createdAt": "2026-09-19T02:08:12.065Z",
    "updatedAt": "2026-09-19T02:18:12.065Z"
  }
];

export const MOCK_BLOOD_SUMMARY: BloodDashboardSummary = {
  "totalBloodBanks": 50,
  "activeBloodBanks": 50,
  "verifiedBloodBanks": 46,
  "totalUnitsAvailable": 3840,
  "totalUnitsReserved": 18,
  "totalEmergencyRequests": 3,
  "activeEmergencies": 2,
  "fulfilledEmergencies": 1,
  "activeTransfers": 1,
  "unitsByBloodGroup": {
    "A+": 480,
    "A-": 85,
    "B+": 520,
    "B-": 70,
    "AB+": 210,
    "AB-": 45,
    "O+": 2180,
    "O-": 250
  },
  "requestsByStatus": {
    "MATCH_FOUND": 1,
    "IN_TRANSIT": 1,
    "FULFILLED": 1
  }
};
