"""
PHC-NET AI: Synthetic Healthcare & Supply-Chain Data Generator
==============================================================
Generates statistically calibrated synthetic datasets for India's Primary Health
Centre (PHC) network. Models realistic correlations between patient footfall,
disease seasonality, acute outbreaks, and medicine consumption.

DISCLAIMER: All data generated by this module is synthetic and intended solely
for software engineering prototyping, simulation, and algorithm verification.
It does not represent confidential medical records or official government logs.
"""

import csv
import json
import math
import os
import random
from datetime import date, datetime, timedelta
from pathlib import Path

# Fix random seed for reproducible benchmark datasets
RANDOM_SEED = 42
random.seed(RANDOM_SEED)

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------------------------
# 1. Geography & District Configurations (Maharashtra Clusters)
# ------------------------------------------------------------------------------
DISTRICT_CONFIGS = [
    {"name": "Pune", "center_lat": 18.5204, "center_lon": 73.8567, "phc_count": 25},
    {"name": "Nashik", "center_lat": 19.9975, "center_lon": 73.7898, "phc_count": 20},
    {"name": "Satara", "center_lat": 17.6805, "center_lon": 74.0183, "phc_count": 20},
    {"name": "Ahmednagar", "center_lat": 19.0948, "center_lon": 74.7480, "phc_count": 20},
    {"name": "Kolhapur", "center_lat": 16.7050, "center_lon": 74.2433, "phc_count": 15},
]

PHC_NAME_PREFIXES = [
    "Alandi", "Shirwal", "Wai", "Khed", "Bhor", "Saswad", "Junnar", "Baramati",
    "Indapur", "Daund", "Manchar", "Loni", "Sinnar", "Yeola", "Niphad", "Trimbak",
    "Dindori", "Igatpuri", "Chandwad", "Deola", "Karad", "Patan", "Mahabaleshwar",
    "Phaltan", "Koregaon", "Khandala", "Medha", "Rahuri", "Sangamner", "Kopargaon",
    "Shrirampur", "Parner", "Shevgaon", "Nevasa", "Pathardi", "Kagal", "Panhala",
    "Shirol", "Hatkanangle", "Radhanagari", "Bhudargad", "Ajara", "Chandgad", "Gadhinglaj"
]

# ------------------------------------------------------------------------------
# 2. Essential Medicines Catalog (20 Drugs across 5 Clinical Categories)
# ------------------------------------------------------------------------------
MEDICINES_CATALOG = [
    # Antibiotics
    {"code": "MED-001", "name": "Amoxicillin 500mg", "category": "Antibiotic", "unit": "Capsule", "safety_stock": 1000, "shelf_life_days": 730, "requires_cold_chain": False, "base_demand_rate": 0.045, "seasonality": "winter"},
    {"code": "MED-002", "name": "Azithromycin 250mg", "category": "Antibiotic", "unit": "Tablet", "safety_stock": 600, "shelf_life_days": 730, "requires_cold_chain": False, "base_demand_rate": 0.025, "seasonality": "winter"},
    {"code": "MED-003", "name": "Ciprofloxacin 500mg", "category": "Antibiotic", "unit": "Tablet", "safety_stock": 800, "shelf_life_days": 730, "requires_cold_chain": False, "base_demand_rate": 0.035, "seasonality": "monsoon"},
    {"code": "MED-004", "name": "Doxycycline 100mg", "category": "Antibiotic", "unit": "Capsule", "safety_stock": 500, "shelf_life_days": 730, "requires_cold_chain": False, "base_demand_rate": 0.020, "seasonality": "monsoon"},
    
    # Analgesics & Antipyretics
    {"code": "MED-005", "name": "Paracetamol 500mg", "category": "Analgesic/Antipyretic", "unit": "Tablet", "safety_stock": 3000, "shelf_life_days": 1095, "requires_cold_chain": False, "base_demand_rate": 0.180, "seasonality": "monsoon"},
    {"code": "MED-006", "name": "Ibuprofen 400mg", "category": "Analgesic/Antipyretic", "unit": "Tablet", "safety_stock": 1200, "shelf_life_days": 730, "requires_cold_chain": False, "base_demand_rate": 0.050, "seasonality": "none"},
    
    # Maternal & Child Health
    {"code": "MED-007", "name": "Oral Rehydration Salts (ORS)", "category": "Maternal & Child Health", "unit": "Sachet", "safety_stock": 2000, "shelf_life_days": 730, "requires_cold_chain": False, "base_demand_rate": 0.120, "seasonality": "monsoon"},
    {"code": "MED-008", "name": "Zinc Sulfate 20mg", "category": "Maternal & Child Health", "unit": "Tablet", "safety_stock": 1500, "shelf_life_days": 730, "requires_cold_chain": False, "base_demand_rate": 0.080, "seasonality": "monsoon"},
    {"code": "MED-009", "name": "Iron Folic Acid (IFA Large)", "category": "Maternal & Child Health", "unit": "Tablet", "safety_stock": 2500, "shelf_life_days": 730, "requires_cold_chain": False, "base_demand_rate": 0.110, "seasonality": "none"},
    {"code": "MED-010", "name": "Albendazole 400mg", "category": "Maternal & Child Health", "unit": "Chewable Tablet", "safety_stock": 800, "shelf_life_days": 1095, "requires_cold_chain": False, "base_demand_rate": 0.030, "seasonality": "none"},
    {"code": "MED-011", "name": "Oxytocin 10 IU/ml", "category": "Maternal & Child Health", "unit": "Ampoule", "safety_stock": 300, "shelf_life_days": 730, "requires_cold_chain": True, "base_demand_rate": 0.015, "seasonality": "none"},

    # Chronic Care (NCDs)
    {"code": "MED-012", "name": "Metformin 500mg", "category": "Chronic Care", "unit": "Tablet", "safety_stock": 2500, "shelf_life_days": 1095, "requires_cold_chain": False, "base_demand_rate": 0.130, "seasonality": "none"},
    {"code": "MED-013", "name": "Amlodipine 5mg", "category": "Chronic Care", "unit": "Tablet", "safety_stock": 2000, "shelf_life_days": 1095, "requires_cold_chain": False, "base_demand_rate": 0.100, "seasonality": "none"},
    {"code": "MED-014", "name": "Atenolol 50mg", "category": "Chronic Care", "unit": "Tablet", "safety_stock": 1500, "shelf_life_days": 730, "requires_cold_chain": False, "base_demand_rate": 0.070, "seasonality": "none"},
    {"code": "MED-015", "name": "Enalapril 5mg", "category": "Chronic Care", "unit": "Tablet", "safety_stock": 1200, "shelf_life_days": 730, "requires_cold_chain": False, "base_demand_rate": 0.055, "seasonality": "none"},

    # Critical & Emergency Care
    {"code": "MED-016", "name": "Anti-Snake Venom (ASV Polyvalent)", "category": "Emergency & Critical", "unit": "Vial", "safety_stock": 50, "shelf_life_days": 730, "requires_cold_chain": True, "base_demand_rate": 0.003, "seasonality": "monsoon"},
    {"code": "MED-017", "name": "Anti-Rabies Vaccine (ARV)", "category": "Emergency & Critical", "unit": "Vial", "safety_stock": 150, "shelf_life_days": 730, "requires_cold_chain": True, "base_demand_rate": 0.008, "seasonality": "none"},
    {"code": "MED-018", "name": "Dexamethasone 4mg/ml", "category": "Emergency & Critical", "unit": "Ampoule", "safety_stock": 400, "shelf_life_days": 730, "requires_cold_chain": False, "base_demand_rate": 0.018, "seasonality": "winter"},
    {"code": "MED-019", "name": "Atropine Sulfate 0.6mg/ml", "category": "Emergency & Critical", "unit": "Ampoule", "safety_stock": 200, "shelf_life_days": 730, "requires_cold_chain": False, "base_demand_rate": 0.006, "seasonality": "none"},
    {"code": "MED-020", "name": "Salbutamol Inhaler 100mcg", "category": "Emergency & Critical", "unit": "Inhaler", "safety_stock": 350, "shelf_life_days": 730, "requires_cold_chain": False, "base_demand_rate": 0.016, "seasonality": "winter"},
]

# ------------------------------------------------------------------------------
# 3. Data Generator Engine
# ------------------------------------------------------------------------------
def generate_phcs():
    """Generates 100 PHCs across 5 districts with realistic coordinates and populations."""
    phcs = []
    phc_id = 1
    name_idx = 0
    
    for dist in DISTRICT_CONFIGS:
        for _ in range(dist["phc_count"]):
            # Small random jitter around district center (~0.05 to 0.3 degrees, roughly 5-35 km)
            lat_jitter = (random.random() - 0.5) * 0.45
            lon_jitter = (random.random() - 0.5) * 0.45
            lat = round(dist["center_lat"] + lat_jitter, 6)
            lon = round(dist["center_lon"] + lon_jitter, 6)
            
            # Log-normal distribution for rural/semi-urban population served
            pop = int(random.lognormvariate(10.35, 0.25))  # mean around 32,000
            
            prefix = PHC_NAME_PREFIXES[name_idx % len(PHC_NAME_PREFIXES)]
            suffix = f"PHC-{phc_id}"
            name = f"{prefix} {suffix}"
            name_idx += 1
            
            phcs.append({
                "id": phc_id,
                "name": name,
                "district": dist["name"],
                "state": "Maharashtra",
                "latitude": lat,
                "longitude": lon,
                "population_served": pop,
                "is_active": True,
            })
            phc_id += 1
            
    return phcs

def generate_medicines():
    """Maps essential medicine list with sequential primary keys."""
    medicines = []
    for idx, med in enumerate(MEDICINES_CATALOG, start=1):
        item = dict(med)
        item["id"] = idx
        medicines.append(item)
    return medicines

def generate_historical_series(phcs, medicines, days=365):
    """
    Generates 365 days of correlated daily footfall and medicine demand.
    - Monday surges, Sunday drop.
    - Monsoon surge (June-Sept).
    - Disease spikes and acute emergency episodes.
    """
    end_date = date.today() - timedelta(days=1)
    start_date = end_date - timedelta(days=days - 1)
    
    footfalls = []
    demands = []
    
    footfall_id = 1
    demand_id = 1
    
    # Pre-calculate outbreak events (specific PHCs experiencing 3-7 day acute outbreaks)
    outbreaks = {}
    for phc in phcs:
        outbreaks[phc["id"]] = []
        if random.random() < 0.6:  # 60% of PHCs had 1 or 2 acute episodes during the year
            num_episodes = random.choice([1, 2])
            for _ in range(num_episodes):
                outbreak_day = random.randint(30, days - 30)
                outbreak_duration = random.randint(3, 7)
                outbreak_type = random.choice(["gastro", "viral_fever", "respiratory"])
                outbreaks[phc["id"]].append((outbreak_day, outbreak_duration, outbreak_type))

    print(f"Generating {days} days of time series for {len(phcs)} PHCs...")
    
    for day_offset in range(days):
        current_date = start_date + timedelta(days=day_offset)
        weekday = current_date.weekday()  # 0=Mon, 6=Sun
        month = current_date.month
        is_monsoon = 6 <= month <= 9
        is_winter = month in [11, 12, 1]
        
        # Day-of-week multiplier
        if weekday == 0:  # Monday rush
            dow_mult = 1.25
        elif weekday == 6:  # Sunday minimum staff/OPD
            dow_mult = 0.55
        elif weekday in [1, 2]:
            dow_mult = 1.08
        else:
            dow_mult = 0.95
            
        # Seasonal footfall multiplier
        season_mult = 1.0
        if is_monsoon:
            season_mult += 0.28
        elif is_winter:
            season_mult += 0.12
            
        for phc in phcs:
            p_id = phc["id"]
            base_daily_patients = phc["population_served"] * 0.0045  # ~140 patients/day
            
            # Check for active outbreak
            outbreak_mult = 1.0
            active_outbreak_type = None
            for ob_day, ob_dur, ob_type in outbreaks[p_id]:
                if ob_day <= day_offset < ob_day + ob_dur:
                    outbreak_mult = 1.65
                    active_outbreak_type = ob_type
                    break
                    
            # Add Gaussian noise
            daily_patients = int(max(15, random.gauss(
                base_daily_patients * dow_mult * season_mult * outbreak_mult,
                base_daily_patients * 0.10
            )))
            
            emergency_count = int(max(0, random.gauss(daily_patients * 0.06, 2)))
            
            footfalls.append({
                "id": footfall_id,
                "phc_id": p_id,
                "record_date": str(current_date),
                "patient_count": daily_patients,
                "emergency_count": emergency_count,
            })
            footfall_id += 1
            
            # Generate medicine consumption correlated with footfall
            for med in medicines:
                m_id = med["id"]
                rate = med["base_demand_rate"]
                med_seasonality = med["seasonality"]
                
                med_mult = 1.0
                if is_monsoon and med_seasonality == "monsoon":
                    med_mult *= 1.75
                elif is_winter and med_seasonality == "winter":
                    med_mult *= 1.50
                    
                # Outbreak boost
                if active_outbreak_type == "gastro" and med["code"] in ["MED-007", "MED-008", "MED-003"]:  # ORS, Zinc, Cipro
                    med_mult *= 2.4
                elif active_outbreak_type == "viral_fever" and med["code"] in ["MED-005", "MED-001"]:  # Paracetamol, Amoxicillin
                    med_mult *= 2.1
                elif active_outbreak_type == "respiratory" and med["code"] in ["MED-001", "MED-002", "MED-020"]:  # Antibiotics, Inhaler
                    med_mult *= 2.2
                    
                expected_demand = daily_patients * rate * med_mult
                actual_demand = int(max(0, round(random.gauss(expected_demand, max(1.0, expected_demand * 0.18)))))
                
                demands.append({
                    "id": demand_id,
                    "phc_id": p_id,
                    "medicine_id": m_id,
                    "record_date": str(current_date),
                    "quantity_used": actual_demand,
                })
                demand_id += 1

    return footfalls, demands

def generate_current_inventories(phcs, medicines, demands):
    """
    Computes realistic current stock balances based on average daily demand.
    Engineers 3 distinct profiles for realistic redistribution simulation:
    - 15 PHCs: CRITICAL DEFICIT (1-3 days of stock remaining)
    - 10 PHCs: SURPLUS OVERSTOCK (30-60 days of stock remaining)
    - 75 PHCs: BALANCED / SAFE (10-20 days of stock remaining)
    """
    # Calculate average daily demand over the last 30 days per (phc, med)
    recent_demand = {}
    for d in demands[-len(phcs) * len(medicines) * 30:]:
        key = (d["phc_id"], d["medicine_id"])
        recent_demand[key] = recent_demand.get(key, 0) + d["quantity_used"]
        
    for k in recent_demand:
        recent_demand[k] = max(1.0, recent_demand[k] / 30.0)

    # Designate deficit and surplus PHCs
    critical_phc_ids = set(range(1, 16))      # PHC 1 to 15: Critical
    surplus_phc_ids = set(range(16, 26))      # PHC 16 to 25: Surplus donors
    # Remaining 75 PHCs: Balanced

    inventories = []
    inv_id = 1
    today = date.today()

    for phc in phcs:
        p_id = phc["id"]
        for med in medicines:
            m_id = med["id"]
            avg_daily = recent_demand.get((p_id, m_id), 15.0)
            
            if p_id in critical_phc_ids:
                # 1 to 3 days of stock left -> triggers CRITICAL / HIGH alerts
                days_stock = random.uniform(1.2, 3.4)
            elif p_id in surplus_phc_ids:
                # 30 to 60 days of stock -> prime candidates for transfer donor
                days_stock = random.uniform(32.0, 58.0)
            else:
                # Balanced: 12 to 22 days of stock
                days_stock = random.uniform(12.0, 22.0)
                
            qty = int(max(5, round(avg_daily * days_stock)))
            reserved = int(qty * 0.05) if p_id in surplus_phc_ids else 0
            
            # Expiry dates between 6 months and 2 years from today
            expiry_days = random.randint(180, 700)
            expiry_date = today + timedelta(days=expiry_days)
            batch = f"BATCH-2026-{m_id:02d}-{p_id:03d}"
            
            inventories.append({
                "id": inv_id,
                "phc_id": p_id,
                "medicine_id": m_id,
                "quantity": qty,
                "reserved_quantity": reserved,
                "batch_number": batch,
                "expiry_date": str(expiry_date),
            })
            inv_id += 1

    return inventories

def generate_default_users():
    """Generates standard administrative and managerial accounts for RBAC."""
    # Bcrypt hash for password 'password123'
    # $2a$10$wT8K5P9Vn1.0oY1j7BqVheK1M4yFqUvH8.8Yx7n5Q3aKjR2vR8eSu (or placeholder hash)
    standard_hash = "$2a$10$7zB3cW0L1J4P8Y9X2T6O0e0mYw0Q4k9F1v3P5q7R9t1Z3b5V7x9A."
    
    users = [
        {
            "id": 1,
            "username": "admin",
            "password_hash": standard_hash,
            "full_name": "State Directorate Administrator",
            "email": "admin@phcnet.gov.in",
            "role": "ROLE_ADMIN",
            "assigned_phc_id": None,
            "assigned_district": None,
            "is_active": True,
        },
        {
            "id": 2,
            "username": "dho_pune",
            "password_hash": standard_hash,
            "full_name": "Dr. Rajesh Sharma (DHO Pune)",
            "email": "dho.pune@phcnet.gov.in",
            "role": "ROLE_DISTRICT_OFFICER",
            "assigned_phc_id": None,
            "assigned_district": "Pune",
            "is_active": True,
        },
        {
            "id": 3,
            "username": "dho_nashik",
            "password_hash": standard_hash,
            "full_name": "Dr. Ananya Joshi (DHO Nashik)",
            "email": "dho.nashik@phcnet.gov.in",
            "role": "ROLE_DISTRICT_OFFICER",
            "assigned_phc_id": None,
            "assigned_district": "Nashik",
            "is_active": True,
        },
        {
            "id": 4,
            "username": "phc_mgr_1",
            "password_hash": standard_hash,
            "full_name": "Sunita Devi (Pharmacist PHC-1)",
            "email": "mgr.phc1@phcnet.gov.in",
            "role": "ROLE_PHC_MANAGER",
            "assigned_phc_id": 1,
            "assigned_district": "Pune",
            "is_active": True,
        },
        {
            "id": 5,
            "username": "phc_mgr_16",
            "password_hash": standard_hash,
            "full_name": "Kavita Patil (Pharmacist PHC-16 Surplus)",
            "email": "mgr.phc16@phcnet.gov.in",
            "role": "ROLE_PHC_MANAGER",
            "assigned_phc_id": 16,
            "assigned_district": "Nashik",
            "is_active": True,
        }
    ]
    return users

# ------------------------------------------------------------------------------
# 4. Exporters (CSV, JSON, and SQL Seeder)
# ------------------------------------------------------------------------------
def export_to_csv(filename, rows, fieldnames):
    filepath = DATA_DIR / filename
    with open(filepath, mode="w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(f"Exported {len(rows):,} rows -> {filepath}")

def generate_sql_seed(phcs, medicines, inventories, footfalls, demands, users):
    """Generates a standalone PostgreSQL seed_data.sql for 1-click loading."""
    sql_path = DATA_DIR / "seed_data.sql"
    print(f"Generating unified SQL seed script: {sql_path} ...")
    
    with open(sql_path, "w", encoding="utf-8") as f:
        f.write("-- PHC-NET AI: Synthetic Seed Data Script\n")
        f.write("-- Auto-generated by generate_synthetic_data.py\n\n")
        f.write("BEGIN;\n\n")
        
        # 1. PHCs
        f.write("-- Insert PHCs\n")
        for p in phcs:
            f.write(f"INSERT INTO phcs (id, name, district, state, latitude, longitude, population_served, is_active) "
                    f"VALUES ({p['id']}, '{p['name']}', '{p['district']}', '{p['state']}', {p['latitude']}, {p['longitude']}, {p['population_served']}, {str(p['is_active']).lower()});\n")
        f.write("SELECT setval('phcs_id_seq', (SELECT MAX(id) FROM phcs));\n\n")
        
        # 2. Medicines
        f.write("-- Insert Medicines\n")
        for m in medicines:
            f.write(f"INSERT INTO medicines (id, code, name, category, unit, safety_stock, shelf_life_days, requires_cold_chain) "
                    f"VALUES ({m['id']}, '{m['code']}', '{m['name']}', '{m['category']}', '{m['unit']}', {m['safety_stock']}, {m['shelf_life_days']}, {str(m['requires_cold_chain']).lower()});\n")
        f.write("SELECT setval('medicines_id_seq', (SELECT MAX(id) FROM medicines));\n\n")

        # 3. Users
        f.write("-- Insert Users\n")
        for u in users:
            phc_val = u['assigned_phc_id'] if u['assigned_phc_id'] is not None else 'NULL'
            dist_val = f"'{u['assigned_district']}'" if u['assigned_district'] is not None else 'NULL'
            f.write(f"INSERT INTO users (id, username, password_hash, full_name, email, role, assigned_phc_id, assigned_district, is_active) "
                    f"VALUES ({u['id']}, '{u['username']}', '{u['password_hash']}', '{u['full_name']}', '{u['email']}', '{u['role']}', {phc_val}, {dist_val}, {str(u['is_active']).lower()});\n")
        f.write("SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));\n\n")

        # 4. Current Inventories
        f.write("-- Insert Current Inventories\n")
        for inv in inventories:
            f.write(f"INSERT INTO inventories (id, phc_id, medicine_id, quantity, reserved_quantity, batch_number, expiry_date) "
                    f"VALUES ({inv['id']}, {inv['phc_id']}, {inv['medicine_id']}, {inv['quantity']}, {inv['reserved_quantity']}, '{inv['batch_number']}', '{inv['expiry_date']}');\n")
        f.write("SELECT setval('inventories_id_seq', (SELECT MAX(id) FROM inventories));\n\n")

        # 5. Historical Footfalls (Batched)
        f.write("-- Insert Patient Footfalls (Recent sample in seed script, complete history in CSV)\n")
        # For seed_data.sql file size safety, output the last 30 days into SQL directly, 
        # while all 365 days are preserved in patient_footfalls.csv
        recent_footfalls = footfalls[-len(phcs) * 30:]
        for ff in recent_footfalls:
            f.write(f"INSERT INTO patient_footfalls (id, phc_id, record_date, patient_count, emergency_count) "
                    f"VALUES ({ff['id']}, {ff['phc_id']}, '{ff['record_date']}', {ff['patient_count']}, {ff['emergency_count']});\n")
        f.write("SELECT setval('patient_footfalls_id_seq', (SELECT MAX(id) FROM patient_footfalls));\n\n")

        # 6. Historical Demands (Last 30 days in SQL, complete 365 days in demands.csv)
        f.write("-- Insert Demands (Recent 30 days sample in seed script, complete history in CSV)\n")
        recent_demands = demands[-len(phcs) * len(medicines) * 30:]
        for dm in recent_demands:
            f.write(f"INSERT INTO demands (id, phc_id, medicine_id, record_date, quantity_used) "
                    f"VALUES ({dm['id']}, {dm['phc_id']}, {dm['medicine_id']}, '{dm['record_date']}', {dm['quantity_used']});\n")
        f.write("SELECT setval('demands_id_seq', (SELECT MAX(id) FROM demands));\n\n")

        f.write("COMMIT;\n")

    print(f"Unified SQL seed generated at: {sql_path}")

def main():
    print("=================================================================")
    print(" PHC-NET AI: Starting Synthetic Data Generation (Milestone 1)")
    print("=================================================================")
    
    start_time = datetime.now()
    
    phcs = generate_phcs()
    medicines = generate_medicines()
    footfalls, demands = generate_historical_series(phcs, medicines, days=365)
    inventories = generate_current_inventories(phcs, medicines, demands)
    users = generate_default_users()
    
    # Export full CSV datasets
    export_to_csv("phcs.csv", phcs, ["id", "name", "district", "state", "latitude", "longitude", "population_served", "is_active"])
    export_to_csv("medicines.csv", medicines, ["id", "code", "name", "category", "unit", "safety_stock", "shelf_life_days", "requires_cold_chain", "base_demand_rate", "seasonality"])
    export_to_csv("inventories.csv", inventories, ["id", "phc_id", "medicine_id", "quantity", "reserved_quantity", "batch_number", "expiry_date"])
    export_to_csv("patient_footfalls.csv", footfalls, ["id", "phc_id", "record_date", "patient_count", "emergency_count"])
    export_to_csv("demands.csv", demands, ["id", "phc_id", "medicine_id", "record_date", "quantity_used"])
    export_to_csv("users.csv", users, ["id", "username", "password_hash", "full_name", "email", "role", "assigned_phc_id", "assigned_district", "is_active"])
    
    # Generate unified SQL seed file
    generate_sql_seed(phcs, medicines, inventories, footfalls, demands, users)
    
    elapsed = (datetime.now() - start_time).total_seconds()
    print("=================================================================")
    print(f" Summary:")
    print(f"  - Total PHCs: {len(phcs):,}")
    print(f"  - Total Medicines: {len(medicines):,}")
    print(f"  - Total Footfall Records (365 days): {len(footfalls):,}")
    print(f"  - Total Demand Records (365 days): {len(demands):,}")
    print(f"  - Current Inventory Records: {len(inventories):,}")
    print(f"  - Completed in: {elapsed:.2f} seconds")
    print("=================================================================")

if __name__ == "__main__":
    main()
